//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamingGateStudios.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Games.
        /// </summary>
        public static string bestgames {
            get {
                return ResourceManager.GetString("bestgames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (You Will Use This Code In Game).
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Buy This Deal (Go To Game To Use It).
        /// </summary>
        public static string DealDone {
            get {
                return ResourceManager.GetString("DealDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GGP Is Less Than Deal GGP.
        /// </summary>
        public static string DealError {
            get {
                return ResourceManager.GetString("DealError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Profile.
        /// </summary>
        public static string EditYourProfile {
            get {
                return ResourceManager.GetString("EditYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Or Password Is Used !!.
        /// </summary>
        public static string emailused {
            get {
                return ResourceManager.GetString("emailused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code Is Used !!.
        /// </summary>
        public static string errorcode {
            get {
                return ResourceManager.GetString("errorcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone And Password Not In This Game !!.
        /// </summary>
        public static string errorgame {
            get {
                return ResourceManager.GetString("errorgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone And Password Not Valid !!.
        /// </summary>
        public static string errorgamer {
            get {
                return ResourceManager.GetString("errorgamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Payment !!.
        /// </summary>
        public static string errorPay {
            get {
                return ResourceManager.GetString("errorPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Data !!.
        /// </summary>
        public static string ErrorSaved {
            get {
                return ResourceManager.GetString("ErrorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Data.
        /// </summary>
        public static string GameData {
            get {
                return ResourceManager.GetString("GameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Password.
        /// </summary>
        public static string GPassword {
            get {
                return ResourceManager.GetString("GPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Phone.
        /// </summary>
        public static string GPhone {
            get {
                return ResourceManager.GetString("GPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore.
        /// </summary>
        public static string Homedescription1 {
            get {
                return ResourceManager.GetString("Homedescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.
        /// </summary>
        public static string Homedescription2 {
            get {
                return ResourceManager.GetString("Homedescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Photo Must Be In (.jpg , .png , .gif , .bmp).
        /// </summary>
        public static string ImageError {
            get {
                return ResourceManager.GetString("ImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Money Token Limit Is Finish.
        /// </summary>
        public static string MoneytokenError {
            get {
                return ResourceManager.GetString("MoneytokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Games.
        /// </summary>
        public static string NewGames {
            get {
                return ResourceManager.GetString("NewGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Games.
        /// </summary>
        public static string Oldgames {
            get {
                return ResourceManager.GetString("Oldgames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Now.
        /// </summary>
        public static string Playnow {
            get {
                return ResourceManager.GetString("Playnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGP Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks Your Prize Will Recive.
        /// </summary>
        public static string prizedone {
            get {
                return ResourceManager.GetString("prizedone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone And Password Not Valid !!.
        /// </summary>
        public static string Prizeerror {
            get {
                return ResourceManager.GetString("Prizeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Point Less Than Prize Points !!.
        /// </summary>
        public static string prizeserrorpoints {
            get {
                return ResourceManager.GetString("prizeserrorpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string redeem {
            get {
                return ResourceManager.GetString("redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error In Redeem !!.
        /// </summary>
        public static string redeemerror {
            get {
                return ResourceManager.GetString("redeemerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeeming Points.
        /// </summary>
        public static string RedeemingPoints {
            get {
                return ResourceManager.GetString("RedeemingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information Saved Successufly.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe For News.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email !!.
        /// </summary>
        public static string VaildEmail {
            get {
                return ResourceManager.GetString("VaildEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners.
        /// </summary>
        public static string winners {
            get {
                return ResourceManager.GetString("winners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
