//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Client_ID { get; set; }
        public bool Enable { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int CPM { get; set; }
        public string Link { get; set; }
        public int Click { get; set; }
    
        public virtual Ads_Clients Ads_Clients { get; set; }
    }
}
