//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads_Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ads_Clients()
        {
            this.ADS = new HashSet<AD>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Target_CPM { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Agency_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD> ADS { get; set; }
        public virtual Agency Agency { get; set; }
    }
}
