//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Member
    {
        public int ID { get; set; }
        public int Deal_ID { get; set; }
        public int Member_ID { get; set; }
        public int GGB { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual MemberShip MemberShip { get; set; }
    }
}
