//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gamer()
        {
            this.Deal_Gamers = new HashSet<Deal_Gamers>();
            this.Winners = new HashSet<Winner>();
        }
    
        public int ID { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Member { get; set; }
        public string Country { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Tries { get; set; }
        public Nullable<double> Mony_Send { get; set; }
        public Nullable<double> Money_Token { get; set; }
        public bool Active { get; set; }
        public int Game_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_Gamers> Deal_Gamers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Winner> Winners { get; set; }
        public virtual Game Game { get; set; }
    }
}
