//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Deals = new HashSet<Deal>();
            this.Gamers = new HashSet<Gamer>();
            this.Splashes = new HashSet<Splash>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_AR { get; set; }
        public string Description { get; set; }
        public string Description_AR { get; set; }
        public string Android_URL { get; set; }
        public string Ituens_URL { get; set; }
        public string Windows_URL { get; set; }
        public string Facebook_URL { get; set; }
        public string KindleFire_URL { get; set; }
        public string EB_URL { get; set; }
        public string Game_Link { get; set; }
        public string Trailer { get; set; }
        public int Watch { get; set; }
        public int Start_Tries { get; set; }
        public int Start_Points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gamer> Gamers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Splash> Splashes { get; set; }
    }
}
