//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Splash
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Channel_ID { get; set; }
        public bool Enable { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Game_ID { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Game Game { get; set; }
    }
}
