//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingGateStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags_Videos
    {
        public int ID { get; set; }
        public int Tag_ID { get; set; }
        public int Video_ID { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Video Video { get; set; }
    }
}
